/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.ui.internal.VideogenActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class VideogenExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return VideogenActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return VideogenActivator.getInstance().getInjector(VideogenActivator.ORG_XTEXT_VIDEOGEN);
	}
	
}
