/*
 * generated by Xtext
 */
package org.xtext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VideogenUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.ui.internal.VideogenActivator.getInstance().getInjector("org.xtext.Videogen");
	}
	
}
