/*
 * generated by Xtext
 */
package org.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VideogenUiModule extends org.xtext.ui.AbstractVideogenUiModule {
	public VideogenUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
